### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by probonopd** [sticilface/ESP8266-wifi#11]
Trying to compile on Arduino 1.6.8 with esp8266/Arduino from git, I get:

```
Arduino: 1.6.8 Hourly Build 2016/01/19 08:26 (Linux), Board: "Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS), ck, Disabled, None"

In file included from /home/me/Downloads/ESP8266-wifi-ESP8266_wifi/Melvana/Melvana.ino:63:0:
/home/me/Arduino/libraries/E131-master/E131.h:143:9: error: '_UDP' does not name a type
         _UDP udp;               /* UDP handle */
         ^
/home/me/Arduino/libraries/E131-master/E131.h: In member function 'uint16_t E131::parsePacket()':
/home/me/Arduino/libraries/E131-master/E131.h:202:24: error: 'udp' was not declared in this scope
             int size = udp.parsePacket();
                        ^
/home/me/Downloads/ESP8266-wifi-ESP8266_wifi/Melvana/c_command_handle.ino: In function 'void ssid_command(String)':
c_command_handle:19: error: 'Save_String' was not declared in this scope
               Save_String(ssid, ssidAddress, ssidAddressbyte);
                                                             ^
/home/me/Downloads/ESP8266-wifi-ESP8266_wifi/Melvana/c_command_handle.ino: In function 'void password_command(String)':
c_command_handle:47: error: 'Save_String' was not declared in this scope
               Save_String(password, passwordAddress, passwordAddressbyte);
                                                                         ^
/home/me/Downloads/ESP8266-wifi-ESP8266_wifi/Melvana/c_command_handle.ino: In function 'void deviceid_command(String)':
c_command_handle:61: error: 'send_mqtt_msg' was not declared in this scope
               send_mqtt_msg(F("status"),"DeviceID-> " + value);
                                                              ^
c_command_handle:67: error: 'Save_String' was not declared in this scope
               Save_String(deviceid, deviceidAddress,deviceidAddressbyte);
                                                                        ^
/home/me/Downloads/ESP8266-wifi-ESP8266_wifi/Melvana/c_command_handle.ino: In function 'void debug_command(String)':
c_command_handle:126: error: 'send_mqtt_msg' was not declared in this scope
     send_mqtt_msg (F("Status"), F("Debug set to timer"));
                                                        ^
c_command_handle:138: error: 'send_mqtt_msg' was not declared in this scope
     send_mqtt_msg (F("Status"), F("Debug disabled"));
                                                    ^
/home/me/Downloads/ESP8266-wifi-ESP8266_wifi/Melvana/c_command_handle.ino: In function 'void mqttreloadfunc()':
c_command_handle:155: error: 'initiatemqqt' was not declared in this scope
       initiatemqqt (); 
                     ^
/home/me/Downloads/ESP8266-wifi-ESP8266_wifi/Melvana/c_plugin_commands.ino: In function 'void handle_root()':
c_plugin_commands:7: error: 'handle_WS2812' was not declared in this scope
   handle_WS2812(); 
                 ^
c_plugin_commands:9: error: 'handle_wifi' was not declared in this scope
   handle_wifi();
               ^
/home/me/Downloads/ESP8266-wifi-ESP8266_wifi/Melvana/c_plugin_commands.ino: At global scope:
c_plugin_commands:19: error: 'MQTT' does not name a type
 void cache mqtt_plugin_handle( const MQTT::Publish& pub ) {
                                      ^
c_plugin_commands:19: error: expected unqualified-id before '&' token
 void cache mqtt_plugin_handle( const MQTT::Publish& pub ) {
                                                   ^
c_plugin_commands:19: error: expected ')' before '&' token
c_plugin_commands:19: error: expected initializer before 'pub'
 void cache mqtt_plugin_handle( const MQTT::Publish& pub ) {
                                                     ^
exit status 1
'Save_String' was not declared in this scope
```

Please document the exact combinations of IDE, core, and libraries you used to compile this.
